#! /bin/sh

sxhkd &
echo '0' > ~/sylveryte/dotfiles/tools/.polybar.data

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc rule -a termite:scratchy sticky=on state=floating rectangle=widthxheight+Xoffset+Yoffset

bspc config border_width         2
bspc config border_radius        4
bspc config window_gap           8

bspc config split_ratio          0.6
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle      true

# --------------------------------
# ------- Non-BSPWM related ------
# --------------------------------
# Reload .Xresources
xrdb -load ~/.Xresources
# Launch polybar
pa-applet &
blueman-applet &
nm-applet &
# Change from ugly 'X' cursor when hovering over background
xsetroot -cursor_name left_ptr
# Make betterlockscreen generate and cache a background image for locking
# sudo betterlockscreen -u ~/Documents/Wallpapers/gruvbox.png
# ------- Autostart apps ------
# Picom
picom --xrender-sync-fence &
# Dunst
dunst &
# Set wallpaper
~/sylveryte/dotfiles/tools/changewal.sh generic
# Nm-applet
# nm-applet &

# ------- Mouse/Touchpad fixes ------
# Start libinput gestures
# libinput-gestures-setup start
# Xinput configs (touchpad)
# xinput set-prop "DLL07BE:01 06CB:7A13 Touchpad" "libinput Natural Scrolling Enabled" 1
# xinput set-prop "DLL07BE:01 06CB:7A13 Touchpad" "libinput Click Method Enabled" 0 1
# xinput set-prop "DLL07BE:01 06CB:7A13 Touchpad" "libinput Disable While Typing Enabled" 0
# ------- Keyboard fixes ------
# Remap Caps-lock key to Escape, for using VIM
# setxkbmap -option caps:escape
# Make US and DK keyboard layout togglable with Shift+Alt
# setxkbmap -layout us,dk -option grp:alt_shift_toggle
