# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.31.3"
neorg = "8.7.1"
"telescope.nvim" = "scm"
"rocks-config.nvim" = "2.0.0"
"rocks-git.nvim" = "1.5.1"
"trouble.nvim" = "3.4.3"
neorg-telescope = "1.1.0"
luasnip = "2.3.0"
"neo-tree.nvim" = "3.26"
"which-key.nvim" = "2.1.0"
"fterm.nvim" = "scm"
nvim-lspconfig = "0.1.8"
"mason.nvim" = "1.10.0"
"mason-lspconfig.nvim" = "1.29.0"
"lualine.nvim" = "scm"
"mini.indentscope" = "0.9.0"
"lspsaga.nvim" = "scm"
"telescope-frecency.nvim" = "scm"
"lspkind.nvim" = "scm"
"image.nvim" = "1.3.0"
"oil.nvim" = "2.10.0"
"tokyonight.nvim" = "3.0.1"
nvim-dbee = "0.1.6"

[plugins."formatter.nvim" ]
git = "mhartington/formatter.nvim"

[plugins.nvim-cmp]
git = "hrsh7th/nvim-cmp"
rev = "v0.0.1"

[plugins.cmp-path ]
git = "hrsh7th/cmp-path"

[plugins.cmp_luasnip]
git = "saadparwaiz1/cmp_luasnip"

[plugins.cmp-tw2css]
git = "jcha0713/cmp-tw2css"
rev = "v1.2.0^{}"

[plugins.cmp-nvim-lsp]
git = "hrsh7th/cmp-nvim-lsp"

[plugins.cmp-buffer]
git = "hrsh7th/cmp-buffer"

[plugins.cmp-cmdline]
git = "hrsh7th/cmp-cmdline"

[plugins."kanagawa.nvim"]
version = "scm"

[plugins."nnn.nvim"]
git = "luukvbaal/nnn.nvim"

[plugins.telescope-zoxide]
git = "jvgrootveld/telescope-zoxide"
rev = "v2.1"

[plugins."leap.nvim"]
git = "ggandor/leap.nvim"

[plugins.nvim-treesitter]
git = "nvim-treesitter/nvim-treesitter"
rev = "v0.9.2^{}"

[plugins.vim-fugitive]
git = "tpope/vim-fugitive"
rev = "v3.7^{}"

[plugins.nvim-surround]
git = "kylechui/nvim-surround"
rev = "v2.3.0"

[plugins.nvim-autopairs]
git = "windwp/nvim-autopairs"

[plugins.vim-system-copy]
git = "christoomey/vim-system-copy"

[plugins.emmet-vim]
git = "mattn/emmet-vim"

[plugins."lsp_signature.nvim"]
git = "ray-x/lsp_signature.nvim"
rev = "v0.3.1"

[plugins.vim-unimpaired]
git = "tpope/vim-unimpaired"
rev = "v2.1^{}"

[plugins.vim-repeat]
git = "tpope/vim-repeat"
rev = "v1.2^{}"

[plugins."gitsigns.nvim"]
git = "lewis6991/gitsigns.nvim"
rev = "v0.9.0"

[plugins."indent-blankline.nvim"]
git = "lukas-reineke/indent-blankline.nvim"
rev = "v3.6.3"

[plugins."telescope-gitmoji.nvim"]
git = "olacin/telescope-gitmoji.nvim"

[plugins.nvim-highlight-colors]
git = "brenoprata10/nvim-highlight-colors"

[plugins."tailwind-tools.nvim"]
git = "luckasRanarison/tailwind-tools.nvim"
rev = "v0.2.0"

[plugins.neorg-conceal-wrap]
git = "benlubas/neorg-conceal-wrap"

[plugins."ts-comments.nvim"]
git = "folke/ts-comments.nvim"
rev = "v1.2.0"

[plugins."bg.nvim"]
git = "typicode/bg.nvim"

[plugins.nvim]
git = "catppuccin/nvim"
rev = "v1.7.0"

[plugins.vim-dadbod]
git = "tpope/vim-dadbod"
rev = "v1.4^{}"

[plugins.vim-dadbod-ui]
git = "kristijanhusak/vim-dadbod-ui"

[plugins.vim-dadbod-completion]
git = "kristijanhusak/vim-dadbod-completion"

# [plugins."auto-dark-mode.nvim"]
# git = "f-person/auto-dark-mode.nvim"

[config]
plugins_dir = "plugins/"
auto_setup = false
